name: aems_main

on:
  push:
    branches: [ main ]
    paths:
     - 'aems/**'
     - '.github/workflows/aems.yml'

jobs:

  deploy:
    name: Build image
    runs-on: ubuntu-latest

    steps:   

    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Install Kubectl
      uses: azure/setup-kubectl@v2.0
      with:
        version: 'v1.21.3'
      id: install



    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: foss-traceability-aems-dev
        IMAGE_TAG: ${{ echo ${github.sha} | cut -b -7  }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:dev . -f aems/Dockerfile
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
 
    - name: Update kube config
      run: aws eks update-kubeconfig --name dev-partchain --region eu-central-1
    - name: Deploy image to Amazon EKS
      run: |
        kubectl set image deployment/aems aems=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -n taas --record

